### ISSUE TITLE
Feature #3

### ISSUE THREAD

**Issue by caguilar1990** [caguilar1990/IWVG.SWC.CeciliaAguilarMendez#2]
1. Crear un método de la clase DecimalCollection
-Multiplicar dos decimales.

Cuando compruebe que funcione cierro el ticket y el hito.

Un saludo

**Comment by fclopezjurado** [comment]
Realizada Mejora #2.

Esta es la segunda mejora, dentro de la propia rama.

Sigo sin estar del todo seguro de saber si es lo que quieres o no.

La primera mejora multiplica todos los números de la colección

El commit associado, para tenerlo como referencia es 1a7150bfb6b16f9b561b89703001bee1f85e32d2
Incluido en la rama develop, tras el merge realizado en bdb182a0b2406969225a30b3e8396be064c56433

La segunda mejora multiplica dos número decimales. La función implementada es capaz de multiplicar cualquier número de la colección, con otro recibido como parámetro.

El commit associado, para tenerlo como referencia es 75496b3b182b202dff78ac033da7e66d5770c7c0
Incluido en la rama develop, tras el merge realizado en 7884997ed67f889afa9f4e52150f3af65389f853

Si después de las dos mejoras, sigue sin ser lo que quieres, te pediría por favor, que fueras más explícita en tu definición.

Un saludo!

Fran

**Comment by caguilar1990** [comment]
Hey, he visto tus cambios, muchas Gracias, 
Perdona si no me he explicado bien, has hecho más de lo que quería :P (me valía con la segunda).
Te cierro el milestone por que ya lo has hecho.
Un saludo
