### ISSUE TITLE
Mejora #2

### ISSUE THREAD

**Issue by caguilar1990** [caguilar1990/IWVG.SWC.CeciliaAguilarMendez#6]
1. Crear un método de la clase User
-Incluir métodos con otras formas de presentar el nombre completo

**Comment by dblascom** [comment]
Realizado + merge con develop

David B.

**Comment by caguilar1990** [comment]
HAs forszado un commit para hacer el merge con develop ?
No veo el mergeee

Gracias

**Comment by dblascom** [comment]
Perdona, se me pasó subirlo. Creo que ya.

David B.

**Comment by caguilar1990** [comment]
perfecto, cierro el tiecket. Muchas gracias.
Una preguntilla, al finalizar tengo que crear un tag?
QUe hay qye entregarle al profesor?

**Comment by dblascom** [comment]
En Moodle en tareas tienes lo que hay que entregar. Te lo copio.

-----------

Indicar la URL del repositorio que se entrega, por ejemplo:

https://github.com/miw-upm/IWVG.SwC,JuanGarcia.git
Indicar la URL de Travis-CI, por ejemplo:

https://travis-ci.org/miw-upm/IWVG.SwC,JuanGarcia
Indicar la nota para cada uno de los programadores, por ejemplo:

Programador1: 0.6
Programador2: 1
Programador3: 0.2
Criterios de evaluación:

+3: Porcentaje de finalización respecto a los requisitos, gestión de ramas
+3: Wiki y Gestión de tickets
+1: Travis
+1, +1, +1: Obtenido en el rol de programador de los tres proyectos
